language: node_js

node_js:
  - stable

cache:
  directories:
    - node_modules

script:
  - ./scripts/sonarqube.sh
  # - npm run test
  # - ./scripts/e2e.sh
addons:
  sauce_connect: true

after_success:
  # - ./scripts/coveralls.sh
